sonar.projectKey=PQC-test4
sonar.projectName=PQC-test4
sonar.projectVersion=1.0

sonar.sources=.
sonar.host.url=http://127.0.0.1:9000
sonar.token=sqp_ce776a931784d717406c8f9e0fda24b39a1253bc

sonar.language=py
sonar.sourceEncoding=UTF-8
